# generated by clj2nix-1.1.0-rc
{ fetchMavenArtifact, fetchgit, lib }:

let repos = [
        "https://repo1.maven.org/maven2/"
        "https://repo.clojars.org/" ];

  in rec {
      makePaths = {extraClasspaths ? []}:
        if (builtins.typeOf extraClasspaths != "list")
        then builtins.throw "extraClasspaths must be of type 'list'!"
        else (lib.concatMap (dep:
          builtins.map (path:
            if builtins.isString path then
              path
            else if builtins.hasAttr "jar" path then
              path.jar
            else if builtins.hasAttr "outPath" path then
              path.outPath
            else
              path
            )
          dep.paths)
        packages) ++ extraClasspaths;
      makeClasspaths = {extraClasspaths ? []}:
       if (builtins.typeOf extraClasspaths != "list")
       then builtins.throw "extraClasspaths must be of type 'list'!"
       else builtins.concatStringsSep ":" (makePaths {inherit extraClasspaths;});
      packageSources = builtins.map (dep: dep.src) packages;
      packages = [
  rec {
    name = "transit-java/com.cognitect";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "transit-java";
      groupId = "com.cognitect";
      sha512 = "e02d1b2eb0b768913f5618b4b68ad0cb39d17e738c5e445c65824662da241f3192ec019ac8153465882475963b3584bf467171c5c945e096d2727b55d8e281ae";
      version = "1.0.371";

    };
    paths = [ src ];
  }

  rec {
    name = "data.json/org.clojure";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "data.json";
      groupId = "org.clojure";
      sha512 = "063ccd32448d277d7716e4aec2694bdbcea00f25c055d7b4adb9b6743f1d95267f81628d784c8fcd7bb48ec372c067b5c807c7c833b42f0663f96198f7092d8a";
      version = "2.5.2";

    };
    paths = [ src ];
  }

  rec {
    name = "clojure/org.clojure";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "clojure";
      groupId = "org.clojure";
      sha512 = "236b69613668941eb0bc610104f1d05d8972b24cca61ec22a0259f7ca81c562bd856cd9d0af6341e8c8049049727613df6d3fda1136c758945d452e2b93b2264";
      version = "1.12.5";

    };
    paths = [ src ];
  }

  rec {
    name = "shadow-cljsjs/thheller";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "shadow-cljsjs";
      groupId = "thheller";
      sha512 = "3d0b79eff075c38389d9f3501c60bf91a28a6ee25fc0a2df3159b365eff556e2ec8499b69860783478705ea33ff18e85fc0150229d5725e58e96f362bdc777f1";
      version = "0.0.22";

    };
    paths = [ src ];
  }

  rec {
    name = "javax.activation-api/javax.activation";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "javax.activation-api";
      groupId = "javax.activation";
      sha512 = "8ee0db43ae402f0079a836ef2bff5d15160e3ff9d585c3283f4cf474be4edd2fcc8714d8f032efd72cae77ec5f6d304fc24fa094d9cdba5cf72966cc964af6c9";
      version = "1.2.0";

    };
    paths = [ src ];
  }

  rec {
    name = "commons-codec/commons-codec";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "commons-codec";
      groupId = "commons-codec";
      sha512 = "da30a716770795fce390e4dd340a8b728f220c6572383ffef55bd5839655d5611fcc06128b2144f6cdcb36f53072a12ec80b04afee787665e7ad0b6e888a6787";
      version = "1.15";

    };
    paths = [ src ];
  }

  rec {
    name = "tools.analyzer/org.clojure";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "tools.analyzer";
      groupId = "org.clojure";
      sha512 = "a99d68868959c7eef901f57dfb2069cc8be9313ecf67c7275eb2291231e344a3d7b8a184ede38780223acee51b9381897696912a02de58242c08164542c47830";
      version = "1.2.0";

    };
    paths = [ src ];
  }

  rec {
    name = "cljs-test-display/com.bhauman";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "cljs-test-display";
      groupId = "com.bhauman";
      sha512 = "d8aafc0214bb3719adbb2c957e6a7c939e0db65a0bf69c4369654f736882c3203a4eeb66670e1da18f60faa8bf97b094712472ce883a5a1a5f8dd52b8e413d96";
      version = "0.1.1";

    };
    paths = [ src ];
  }

  rec {
    name = "shadow-http/com.thheller";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "shadow-http";
      groupId = "com.thheller";
      sha512 = "6e9b9e820bb9d7d16f055404360d5399a6e38ffc395e9e0d7c6aad63eade4f0b3af404112d02d0eba05c3f1ae50c2b5d2df807e0a1062a1b1114645f0e0a05cc";
      version = "0.1.8";

    };
    paths = [ src ];
  }

  rec {
    name = "core.specs.alpha/org.clojure";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "core.specs.alpha";
      groupId = "org.clojure";
      sha512 = "d186fe9ac480ab7be989c6174d3931d1530856957177b1ee2794cb5ff6c4173467ff34c7e929e1a2b34d4b0e25abd7707f8d572db4c52e43c7218eac8822938f";
      version = "0.4.74";

    };
    paths = [ src ];
  }

  rec {
    name = "expound/expound";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "expound";
      groupId = "expound";
      sha512 = "810832065897f33fd105aaf84984ee994ec5d90fe60d1a772b083bc2b1c59ff8e9e368bc0f456468824a65694f58cd47149f40b95488947ec5e5e96b44d44d1d";
      version = "0.9.0";

    };
    paths = [ src ];
  }

  rec {
    name = "spec.alpha/org.clojure";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "spec.alpha";
      groupId = "org.clojure";
      sha512 = "2ac83d13ed607b19c1ca651ea54587bf502f0ee89ca042d0f79711e862ea83dbb5326db05523ede58529a258a3fa018e23363740c67b66c682aaf73260b23fab";
      version = "0.5.238";

    };
    paths = [ src ];
  }

  rec {
    name = "tools.cli/org.clojure";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "tools.cli";
      groupId = "org.clojure";
      sha512 = "6ff7e8805c246e8c999b8d1da4ece0dc848dccf23d5beaac5327b891a00da000cc1cc5ef8d7025b38ea27969827a695c100eaa7e69fb77454361aa46f4c9f033";
      version = "1.1.230";

    };
    paths = [ src ];
  }

  rec {
    name = "tools.analyzer.jvm/org.clojure";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "tools.analyzer.jvm";
      groupId = "org.clojure";
      sha512 = "5f882981c5e00fe060caa006e8309c32f5f424f9224bdb1fcbe5ec83fd32f6f32052ef3933c678bb5be8885ca8c12e0b20a3090268cb9e890f2bd30c592ba680";
      version = "1.3.3";

    };
    paths = [ src ];
  }

  rec {
    name = "json-simple/com.googlecode.json-simple";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "json-simple";
      groupId = "com.googlecode.json-simple";
      sha512 = "f8798bfbcc8ab8001baf90ce47ec2264234dc1da2d4aa97fdcdc0990472a6b5a5a32f828e776140777d598a99d8a0c0f51c6d0767ae1a829690ab9200ae35742";
      version = "1.1.1";

    };
    paths = [ src ];
  }

  rec {
    name = "transit-cljs/com.cognitect";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "transit-cljs";
      groupId = "com.cognitect";
      sha512 = "a8cb6bb4f23867fd79ca46619278aae1a53e9e171216d1cf7ed9ba157dbd6a0798e5440a080a2fc0a9498781598681ec4644dcf317bebefbf74bb6c9f47273d2";
      version = "0.8.280";

    };
    paths = [ src ];
  }

  rec {
    name = "google-closure-library/org.clojure";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "google-closure-library";
      groupId = "org.clojure";
      sha512 = "98f10f546edbe75352aee5600870ac636dfd541472b3f54379b71157361e21154f0fcdcc137b01626e38ac55481ca03fbb2f482c845cbccc740ecb3bc1f3917e";
      version = "0.0-20250515-f04e4c0e";

    };
    paths = [ src ];
  }

  rec {
    name = "shadow-cljs/thheller";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "shadow-cljs";
      groupId = "thheller";
      sha512 = "25c7c9780d73b4cbe085342c88d64a5afc8c173415c11c47154ce370def85a8721ad4ad67752f7ef1070f2d5856c998f79efb43654e6ed22749ec158b57710a5";
      version = "3.4.11";

    };
    paths = [ src ];
  }

  rec {
    name = "clojurescript/org.clojure";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "clojurescript";
      groupId = "org.clojure";
      sha512 = "2d7c83194e4d3d2a8e45dc7b3542427e4876b0bdc40d7ea54cb52604eeed54265f9bda4cd89276441266058b3b8c7a30b47692e10df06023c3665c9711fbd7cf";
      version = "1.12.134";

    };
    paths = [ src ];
  }

  rec {
    name = "commons-io/commons-io";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "commons-io";
      groupId = "commons-io";
      sha512 = "fea08e150473673b0608eaee3ae1cb4e73834039db80d3b758710d6baf3a5840a0878a4eb64739ae9bb21ccc7148c8520fe873616a3f6d5cdb4305deabdd015c";
      version = "2.20.0";

    };
    paths = [ src ];
  }

  rec {
    name = "fipp/fipp";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "fipp";
      groupId = "fipp";
      sha512 = "d731e06ce832f7dc9f9788e73bf53f7c406ce6065fbac9f668b4cef38595b23810072fe2b39524dbc6a01ae91916214e1edd91619bf976006ddd18e88102617c";
      version = "0.6.27";

    };
    paths = [ src ];
  }

  rec {
    name = "jackson-core/com.fasterxml.jackson.core";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "jackson-core";
      groupId = "com.fasterxml.jackson.core";
      sha512 = "208953cf72691b3bab1ca2f9a045cccd3d75c46c90099ba884fbf16bc3e45045e5cd014d2c68c96e8a8826f87a5f0e18cb34b35e7ef03348953869c21e197367";
      version = "2.14.2";

    };
    paths = [ src ];
  }

  rec {
    name = "commons-fileupload2-core/org.apache.commons";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "commons-fileupload2-core";
      groupId = "org.apache.commons";
      sha512 = "c2dcb708c0c9f70e53b1704088512a1cd566921734079e008f665fe9bfbdd06b05e24fed352a06a1e2f27e576a72ba81006cc0d85d684b1a08d3f6f54213a777";
      version = "2.0.0-M4";

    };
    paths = [ src ];
  }

  rec {
    name = "asm/org.ow2.asm";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "asm";
      groupId = "org.ow2.asm";
      sha512 = "876eac7406e60ab8b9bd6cd3c221960eaa53febea176a88ae02f4fa92dbcfe80a3c764ba390d96b909c87269a30a69b1ee037a4c642c2f535df4ea2e0dd499f2";
      version = "9.2";

    };
    paths = [ src ];
  }

  rec {
    name = "shadow-util/thheller";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "shadow-util";
      groupId = "thheller";
      sha512 = "803a068159276f5abf6d9cfa25f5c446c4c66d2eaec78393910cb2175b63a734c7c7effaf3064789608b1cf3899c287611c2d170fd78621193acc1fbbff1d5da";
      version = "0.7.0";

    };
    paths = [ src ];
  }

  rec {
    name = "transit-js/com.cognitect";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "transit-js";
      groupId = "com.cognitect";
      sha512 = "bab8c657449a1d01e884923b77c5ef3d7a1a246c3ad1bd85a5b0c98b7952dbdeea97ce7d340ab50aa0dca647a1ef7eb846a52a1a4eecc55e1ff22145b8e820fe";
      version = "0.8.874";

    };
    paths = [ src ];
  }

  rec {
    name = "google-closure-library-third-party/org.clojure";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "google-closure-library-third-party";
      groupId = "org.clojure";
      sha512 = "13d07c9f954764ebab18ea97fd7aac66ee08521d4db52bc986884b8cda942890012c2910ca438bde4070894eac79e1278f76d0479c46b32f0937e176501daec6";
      version = "0.0-20250515-f04e4c0e";

    };
    paths = [ src ];
  }

  rec {
    name = "hiccup/hiccup";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "hiccup";
      groupId = "hiccup";
      sha512 = "034f15be46c35029f41869c912f82cb2929fbbb0524ea64bd98dcdb9cf09875b28c75e926fa5fff53942b0f9e543e85a73a2d03c3f2112eecae30fcef8b148f4";
      version = "1.0.5";

    };
    paths = [ src ];
  }

  rec {
    name = "javassist/org.javassist";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "javassist";
      groupId = "org.javassist";
      sha512 = "ad65ee383ed83bedecc2073118cb3780b68b18d5fb79a1b2b665ff8529df02446ad11e68f9faaf4f2e980065f5946761a59ada379312cbb22d002625abed6a4f";
      version = "3.18.1-GA";

    };
    paths = [ src ];
  }

  rec {
    name = "priority-queue/shams";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "priority-queue";
      groupId = "shams";
      sha512 = "0fe37b55324e7c6bfcd338e7f72cdbaa5987c918877469685e3e23a34da0e8657c6453bf8af5378bb21ba2eff57c767857306ebcba4676525602e07c91194f8c";
      version = "0.1.2";

    };
    paths = [ src ];
  }

  rec {
    name = "msgpack/org.msgpack";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "msgpack";
      groupId = "org.msgpack";
      sha512 = "a2741bed01f9c37ba3dbe6a7ab9ce936d36d4da97c35e215250ac89ac0851fc5948d83975ea6257d5dce1d43b6b5147254ecfb4b33f9bbdc489500b3ff060449";
      version = "0.6.12";

    };
    paths = [ src ];
  }

  rec {
    name = "transit-clj/com.cognitect";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "transit-clj";
      groupId = "com.cognitect";
      sha512 = "a0aa547ec2f11221d1156c4388dea27bfd48470cc0da6dd3702e98530a3cdda146defb5309b5aea60770fb2282e329816ea6b6fbb4349eaf89b310df8003d733";
      version = "1.0.333";

    };
    paths = [ src ];
  }

  rec {
    name = "crypto-random/crypto-random";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "crypto-random";
      groupId = "crypto-random";
      sha512 = "3520df744f250dbe061d1a5d7a05b7143f3a67a4c3f9ad87b8044ee68a36a702a0bcb3a203e35d380899dd01c28e01988b0a7af914b942ccbe0c35c9bdb22e11";
      version = "1.2.1";

    };
    paths = [ src ];
  }

  rec {
    name = "closure-compiler/com.google.javascript";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "closure-compiler";
      groupId = "com.google.javascript";
      sha512 = "c2f8a1278e64fd9b0421ecfc763037ced5f2609c6561c4a1822f544f2ed9d98d7989a50a92f0d8e33a2c68a87609ec833f4fdef622cbcb094d349843250619ef";
      version = "v20250820";

    };
    paths = [ src ];
  }

  rec {
    name = "ring-codec/ring";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "ring-codec";
      groupId = "ring";
      sha512 = "65df7fe417fada187554a0a92d9f0b72972328e7943419066404dbf9443508b5ee156b844d15e3ebdca43de49d7c5fb853469bec44ca7b0dd0d693cf5b93de2a";
      version = "1.3.0";

    };
    paths = [ src ];
  }

  rec {
    name = "shadow-client/thheller";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "shadow-client";
      groupId = "thheller";
      sha512 = "e8019544a1cbbc9c3c9a931bd8dd9b7734260aca9d5e9a7a91089e898c65bee4ab535019c53b917f57c0aa49c1645296966226e4105b45463bbff2f30c7f427c";
      version = "1.4.0";

    };
    paths = [ src ];
  }

  rec {
    name = "core.rrb-vector/org.clojure";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "core.rrb-vector";
      groupId = "org.clojure";
      sha512 = "8204b559d2704105741e1c9a5b8c639161a4f4af09e18b93d6af23685dd8bdebd66b64e626a4daa69069759c423640b3a3787216b78c2e62c891650e2269e8a0";
      version = "0.1.2";

    };
    paths = [ src ];
  }

  rec {
    name = "ring-websocket-protocols/org.ring-clojure";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "ring-websocket-protocols";
      groupId = "org.ring-clojure";
      sha512 = "907fd4f6214131159eb24e998a7f76e05438e40756d65a8f961b49d86ff39cd40cfcf0daa065a1706a2324479c3ef9c3e44013d69aa85d4284ca8a334899c7a8";
      version = "1.15.3";

    };
    paths = [ src ];
  }

  rec {
    name = "crypto-equality/crypto-equality";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "crypto-equality";
      groupId = "crypto-equality";
      sha512 = "4430da47874ce0cbeb22d46141d6c8c352efb7a5bd100aceba1279964d063cfe850998c79d0bfaaa674ca93a47bcdc2bc5dc8f62f7224d9fbf461e00fcba58fc";
      version = "1.0.1";

    };
    paths = [ src ];
  }

  rec {
    name = "tools.reader/org.clojure";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "tools.reader";
      groupId = "org.clojure";
      sha512 = "1216f54eb088bdcd72fe08ed62e78bb8f5bfd9fd46d99a935db3dba1e17bf6935fdcf379a49eb42d5da6af524c3f39be07415fd79121abec7f9d76425cfca032";
      version = "1.6.0";

    };
    paths = [ src ];
  }

  rec {
    name = "ring-core-protocols/org.ring-clojure";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "ring-core-protocols";
      groupId = "org.ring-clojure";
      sha512 = "f60e0e0ad86eafb7a936a803a5a45a0bfe83c246b8ca72110e1493eebb64ac086e0764919aa70f43db58f001c5aba23a676a1d0facbe7b70b9d295a8eb8ec0e2";
      version = "1.15.3";

    };
    paths = [ src ];
  }

  rec {
    name = "replicant/no.cjohansen";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "replicant";
      groupId = "no.cjohansen";
      sha512 = "f71df5042478f2b26c496110dc2082074401305f40ffc78d8225f724a8596242a252477ec4fe8384f2e6681dfbae60d6dd6301f0f71cd5f6ff4bebe498904742";
      version = "2025.12.1";

    };
    paths = [ src ];
  }

  rec {
    name = "nrepl/nrepl";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "nrepl";
      groupId = "nrepl";
      sha512 = "3471ec735fb294d9dbbf5806213cfb9359a76870d2a018645701490eda70c76342e7bf21190ac65702557fbea3af92270224549209cf4b03a8e12299d01d7f44";
      version = "1.3.1";

    };
    paths = [ src ];
  }

  rec {
    name = "core.memoize/org.clojure";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "core.memoize";
      groupId = "org.clojure";
      sha512 = "9441e7d0d61fb1665929a32464d8bacb5c4e9bbef062eb7fc72e39e7402e0bfd32fda4cf05df0c82c60f06936ba152cb73b42d79993ff146c1084640f4205124";
      version = "1.1.266";

    };
    paths = [ src ];
  }

  rec {
    name = "data.priority-map/org.clojure";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "data.priority-map";
      groupId = "org.clojure";
      sha512 = "b90a9a049c6dc0274286e44bcc52bd231065161612eaff920381f3d41bbb28ae22771831ddd03b32e52d089c83ca8a6df6d1d3044977c287f040aaa713b5dc6d";
      version = "1.2.0";

    };
    paths = [ src ];
  }

  rec {
    name = "piggieback/cider";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "piggieback";
      groupId = "cider";
      sha512 = "0f2e70002ef02568125c78c14266d23f43fb0ad477d05db697c0cc13b707bc1a0eacdce0f065f0eaaa68caffc3fb71384499ece45859f07fb1e6bc6d334bf86e";
      version = "0.6.0";

    };
    paths = [ src ];
  }

  rec {
    name = "ring-core/ring";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "ring-core";
      groupId = "ring";
      sha512 = "ef20a3654a3acb2b6e69255a984636299777d73f834662770a986456c7d381e4d9b8532a32804a8cc7fffeea9bcf5e139a0c0ba7c216555e428172494d8ad049";
      version = "1.15.3";

    };
    paths = [ src ];
  }

  rec {
    name = "core.cache/org.clojure";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "core.cache";
      groupId = "org.clojure";
      sha512 = "db8044d17fe8f45ced70f38d1b91f95d2bddfaf3512fa53273c50576c6324cb2df72174fce3d9fce1d5b19da7bdd9e7a00f31359472515d554a6d5414016b5c8";
      version = "1.1.234";

    };
    paths = [ src ];
  }

  rec {
    name = "core.async/org.clojure";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "core.async";
      groupId = "org.clojure";
      sha512 = "46f7c64d1076ef3b9c27e254ca2ddfa0a2ff84d6bfc994d14dbffaade3fce5319d054c61f9aa2bc3b0de7fcc61129e9cb26912b9711ac16bf6cc8b25eee9ea50";
      version = "1.9.865";

    };
    paths = [ src ];
  }

  rec {
    name = "jaxb-api/javax.xml.bind";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "jaxb-api";
      groupId = "javax.xml.bind";
      sha512 = "1d9e270e7ae1ab6bf3ad8c85b044096a58716180daeb9ffa181230b1d8862812954d4d2d3162b24cb2f1c947e998a186581259094e05ad875416488ca7dc3932";
      version = "2.4.0-b180830.0359";

    };
    paths = [ src ];
  }

  ];
  }
  